export type ReviewedEffectCategory =
  | "derived-state"
  | "dom-layout"
  | "event-migration"
  | "external-sync"
  | "identity-reset"
  | "ref-mirror"
  | "request-bridge";

export const reviewedEffectClassifications: Record<ReviewedEffectCategory, readonly string[]> = {
  "external-sync": [
    "apps/web/src/features/notifications/use-push-notifications.ts::usePushNotifications::useEffect::328c4b072fc3::1",
    "apps/web/src/features/pull-to-refresh/PullToRefreshContainer.tsx::PullToRefreshContainer::useEffect::bf260e95d855::1",
    "apps/web/src/features/pull-to-refresh/PullToRefreshContainer.tsx::PullToRefreshContainer::useEffect::e9d7ab33ffca::1",
    "apps/web/src/features/pwa-tabs/context/workspace-tabs-context.tsx::useDismissMissingWorkspaceSessionTabs::useEffect::8fcf0bed1565::1",
    "apps/web/src/features/pwa-tabs/context/workspace-tabs-context.tsx::WorkspaceTabsProvider::useEffect::3faf05c31f97::1",
    "apps/web/src/features/pwa-tabs/context/workspace-tabs-context.tsx::WorkspaceTabsProvider::useEffect::9189f0db7e20::1",
    "apps/web/src/features/shared-session-ui/components/PaneTextComposer.tsx::PaneTextComposer::useEffect::b218bf0d1c11::1",
    "apps/web/src/features/shared-session-ui/components/QuickPanel.tsx::QuickPanel::useEffect::075fa1b6d9a4::1",
    "apps/web/src/features/shared-session-ui/components/QuickPanel.tsx::QuickPanel::useEffect::2a3a2df34ba7::1",
    "apps/web/src/features/shared-session-ui/components/QuickPanel.tsx::useQuickPanelPhase::useEffect::697681af8d3f::1",
    "apps/web/src/features/shared-session-ui/hooks/useRawInputHandlers.ts::useRawInputHandlers::useEffect::8094c05ea1d2::1",
    "apps/web/src/features/shared-session-ui/hooks/useSessionLogs.ts::useSessionLogs::useEffect::c18d345646d2::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreviewHoverController.ts::useSidebarPreviewHoverController::useEffect::8b14324ed70a::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreviewHoverController.ts::useSidebarPreviewHoverController::useEffect::97ac27dbdd61::1",
    "apps/web/src/features/shared-session-ui/hooks/useUserScrollState.ts::useUserScrollState::useLayoutEffect::a2c96aeb1781::1",
    "apps/web/src/lib/use-now-ms.ts::useNowMs::useEffect::151d351581f8::1",
    "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::2a2f791d488d::1",
    "apps/web/src/lib/use-timeout.ts::useTimeout::useEffect::905b6ec3e0b7::1",
    "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::2f04fbcab143::1",
    "apps/web/src/pages/ChatGrid/components/ChatGridCandidateModal.tsx::ChatGridCandidateModalContent::useEffect::375bf343d7c8::1",
    "apps/web/src/pages/ChatGrid/useChatGridVM.ts::useChatGridVM::useEffect::d50d02338726::1",
    "apps/web/src/pages/SessionDetail/components/FileContentModal.tsx::FileContentModal::useEffect::5d33b9b75213::1",
    "apps/web/src/pages/SessionDetail/components/ShikiCodeBlock.tsx::ShikiCodeBlock::useEffect::e89ce58255b1::1",
    "apps/web/src/pages/SessionDetail/components/SmartScreenViewport.tsx::SmartScreenViewport::useEffect::0ceeaf7c4bc9::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenPanelWorktreeSelector.ts::useScreenPanelWorktreeSelector::useEffect::0d53964fa26c::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenPanelWorktreeSelector.ts::useScreenPanelWorktreeSelector::useEffect::37e2ed92c120::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenPollingPauseReason.ts::useScreenPollingPauseReason::useEffect::c4ff4b6900ea::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenScroll.ts::useScreenScroll::useEffect::3b4c5582ebea::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenStream.ts::useScreenStream::useEffect::e50d2dcbba6b::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenWrapMode.ts::useScreenWrapMode::useEffect::87b0178108f7::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionCommits.ts::useSessionCommits::useEffect::b96fa47d4655::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles-file-modal-actions.ts::useSessionFilesFileModalActions::useEffect::2c1e1c2cb570::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles-file-modal-actions.ts::useSessionFilesFileModalActions::useEffect::498f072fe365::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualBranch.ts::useSessionVirtualBranch::useEffect::68821a0ce2a8::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualWorktree.ts::useSessionVirtualWorktree::useEffect::473714e313cc::1",
    "apps/web/src/pages/SessionDetail/SessionDetailView.tsx::useMissingSessionGrace::useEffect::a1f87630f780::1",
    "apps/web/src/pages/SessionList/SessionListView.tsx::SessionListView::useEffect::1a27dd1f1351::1",
    "apps/web/src/state/session-context.tsx::SessionRuntime::useEffect::e55164567bbb::1",
    "apps/web/src/state/theme-context.tsx::ThemeProvider::useLayoutEffect::872c0dc15c2c::1",
    "apps/web/src/state/use-session-token.ts::useSessionToken::useEffect::f7e5f0a4b8c3::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::50e36f40993d::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::ca473e96971b::1",
  ],
  "dom-layout": [
    "apps/web/src/components/ui/file-path-label-utils.ts::useOverflowTruncate::useLayoutEffect::f5edfdfacd6f::1",
    "apps/web/src/components/ui/file-path-label-utils.ts::useSegmentTruncate::useLayoutEffect::2d57bf053bec::1",
    "apps/web/src/features/pwa-tabs/components/PwaWorkspaceTabs.tsx::PwaWorkspaceTabs::useEffect::72ee8e091f65::1",
    "apps/web/src/features/pwa-tabs/components/PwaWorkspaceTabs.tsx::PwaWorkspaceTabs::useLayoutEffect::6391d424a5ab::1",
    "apps/web/src/features/shared-session-ui/components/AnsiVirtualizedViewport.tsx::AnsiVirtualizedViewport::useLayoutEffect::2412ec756366::1",
    "apps/web/src/features/shared-session-ui/components/AnsiVirtualizedViewport.tsx::AnsiVirtualizedViewport::useLayoutEffect::fa3eccb3d534::1",
    "apps/web/src/features/shared-session-ui/components/LogModal.tsx::LogModal::useLayoutEffect::86d02ab4fc38::1",
    "apps/web/src/features/shared-session-ui/components/PaneTextComposer.tsx::PaneTextComposer::useEffect::6e7b516db1d4::1",
    "apps/web/src/features/shared-session-ui/components/PaneTextComposer.tsx::useRevealPromptCompletion::useEffect::acb305abb898::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreviewHoverController.ts::useSidebarPreviewHoverController::useEffect::8af13f227a3c::1",
    "apps/web/src/pages/ChatGrid/components/ChatGridTile.tsx::ChatGridTile::useEffect::5f9329c7582f::1",
    "apps/web/src/pages/ChatGrid/components/ChatGridTile.tsx::useChatGridScreenViewport::useLayoutEffect::56d272f4b5b1::1",
    "apps/web/src/pages/SessionDetail/components/SessionHeader.tsx::SessionTitleInput::useEffect::b2a516a6e032::1",
    "apps/web/src/pages/SessionDetail/components/ShikiCodeBlock.tsx::ShikiCodeBlock::useLayoutEffect::77d6be1a2097::1",
    "apps/web/src/pages/SessionDetail/components/ShikiCodeBlock.tsx::ShikiCodeBlock::useLayoutEffect::a879e383542e::1",
    "apps/web/src/pages/SessionDetail/components/ShikiCodeBlock.tsx::ShikiCodeBlock::useLayoutEffect::acc8bd605571::1",
    "apps/web/src/pages/SessionDetail/components/SmartScreenViewport.tsx::SmartScreenViewport::useEffect::5466a2a944e2::1",
    "apps/web/src/pages/SessionDetail/components/SmartScreenViewport.tsx::SmartScreenViewport::useLayoutEffect::f755299f0b7a::1",
    "apps/web/src/pages/SessionDetail/hooks/useNoteAutoFocus.ts::useNoteAutoFocus::useEffect::8a50e52965fe::1",
    "apps/web/src/pages/SessionDetail/hooks/usePromptContextLayout.ts::usePromptContextLayout::useEffect::d4dbcfbf3f1b::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenScroll.ts::useScreenScroll::useLayoutEffect::2aec0f400dc3::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDetailSectionTabs.ts::useSessionDetailSectionTabs::useEffect::087d9f29555e::1",
    "apps/web/src/pages/SessionList/components/SessionListHeader.tsx::SessionListSearchInput::useEffect::27775dac2407::1",
  ],
  "request-bridge": [
    "apps/web/src/features/launch-agent/LaunchAgentButton.tsx::LaunchAgentButton::useEffect::dc07e9637a44::1",
    "apps/web/src/features/shared-session-ui/components/prompt-completion/usePromptCompletion.ts::usePromptCompletion::useEffect::1d84be3c4035::1",
    "apps/web/src/features/shared-session-ui/hooks/useMultiPaneScreenFeed.ts::useMultiPaneScreenFeed::useEffect::3bf48638a3f5::1",
    "apps/web/src/features/shared-session-ui/hooks/useSessionLogs.ts::useSessionLogs::useEffect::e9f979781eef::1",
    "apps/web/src/pages/SessionDetail/components/DiffPatch.tsx::<module>::useEffect::4f7a397b4bfe::1",
    "apps/web/src/pages/SessionDetail/components/FileContentModal.tsx::FileContentModal::useEffect::3bca156e3280::1",
    "apps/web/src/pages/SessionDetail/hooks/useNotesPolling.ts::useNotesPolling::useEffect::0bb3b3edd6b0::1",
    "apps/web/src/pages/SessionDetail/hooks/useScopeGuard.ts::useScopeGuard::useEffect::1b4336e2733d::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useEffect::9acec1c5844e::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenPanelLogReferenceLinking.ts::useScreenPanelLogReferenceLinking::useEffect::bdbf0aacc451::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionBranches.ts::useSessionBranches::useEffect::7e6d060bba55::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionCommits.ts::useSessionCommits::useEffect::6e529c21830b::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDiffs.ts::useSessionDiffs::useEffect::453daefb092b::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDoneAcknowledgement.ts::useSessionDoneAcknowledgement::useEffect::d71b92eb73c7::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles-search-effects.ts::useSessionFilesSearchEffects::useEffect::08bd638307a8::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionRepoNotes.ts::useSessionRepoNotes::useEffect::bffd15f6ee3e::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionTimeline.ts::useSessionTimeline::useEffect::3d31067cccc7::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionTimeline.ts::useSessionTimeline::useEffect::a7d1185048b8::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualWorktree.ts::useSessionVirtualWorktree::useEffect::d290c3f56a20::1",
    "apps/web/src/pages/UsageDashboard/useRepositoryActivityData.ts::useRepositoryActivityData::useEffect::aa6b86e68fd4::1",
    "apps/web/src/pages/UsageDashboard/useUsageDashboardData.ts::useUsageDashboardData::useEffect::3bb65cbc9349::1",
    "apps/web/src/pages/UsageDashboard/useUsageTimelineData.ts::useUsageTimelineData::useEffect::5e0909d43bf2::1",
    "apps/web/src/state/use-session-polling.ts::useSessionPolling::useEffect::cc037ef9dc2a::1",
  ],
  "event-migration": [
    "apps/web/src/features/pwa-tabs/context/workspace-tabs-context.tsx::WorkspaceTabsProvider::useEffect::17ed7cb77c75::1",
    "apps/web/src/features/shared-session-ui/hooks/useMultiPaneScreenFeed.ts::useMultiPaneScreenFeed::useEffect::6d64e689e2bc::1",
    "apps/web/src/features/shared-session-ui/hooks/useSessionListPins.ts::useSessionListPins::useEffect::84cb69ef4f82::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreview.ts::useSidebarPreview::useEffect::aa1088ea41c5::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreviewTimelineCache.ts::useSidebarPreviewTimelineCache::useEffect::5acc826090a5::1",
    "apps/web/src/lib/use-sidebar-width.ts::useSidebarWidth::useEffect::eca987873fee::1",
    "apps/web/src/lib/use-split-ratio.ts::useSplitRatio::useEffect::4e08c92e0047::1",
    "apps/web/src/pages/SessionDetail/hooks/useNoteAutoSave.ts::useNoteAutoSave::useEffect::96f8b78d6775::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDetailSectionTabs.ts::useSessionDetailSectionTabs::useEffect::5846f3a7adf5::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualBranch.ts::useSessionVirtualBranch::useEffect::2df50698dd4c::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualWorktree.ts::useSessionVirtualWorktree::useEffect::3d9096146aab::1",
    "apps/web/src/pages/SessionList/useSessionListVM.ts::useSessionListVM::useEffect::856c5c339c73::1",
  ],
  "derived-state": [
    "apps/web/src/features/launch-agent/ResumeWorktreeDialog.tsx::ResumeWorktreeDialog::useEffect::7fdbc4714ed5::1",
    "apps/web/src/pages/SessionDetail/components/DiffSection.tsx::<module>::useEffect::de65e42cb91f::1",
    "apps/web/src/pages/SessionDetail/components/SmartScreenViewport.tsx::SmartScreenViewport::useEffect::978b16c4e7d6::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles-search-effects.ts::useSessionFilesSearchEffects::useEffect::6828bf310020::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionScreen.ts::useSessionScreen::useEffect::ecf30f99492b::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualBranch.ts::useSessionVirtualBranch::useEffect::cfedbaac1736::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualWorktree.ts::useSessionVirtualWorktree::useEffect::9b36df59b8d7::1",
  ],
  "ref-mirror": [
    "apps/web/src/features/notifications/use-push-notifications.ts::usePushNotifications::useEffect::c94bf5cf906f::1",
    "apps/web/src/features/pull-to-refresh/PullToRefreshContainer.tsx::PullToRefreshContainer::useEffect::b3d236225390::1",
    "apps/web/src/features/shared-session-ui/components/AnsiVirtualizedViewport.tsx::AnsiVirtualizedViewport::useLayoutEffect::852dbe412eb2::1",
    "apps/web/src/features/shared-session-ui/components/AnsiVirtualizedViewport.tsx::AnsiVirtualizedViewport::useLayoutEffect::b808cf29ed19::1",
    "apps/web/src/features/shared-session-ui/hooks/useRawInputHandlers.ts::useRawInputHandlers::useLayoutEffect::3009e1fcea0e::1",
    "apps/web/src/features/shared-session-ui/hooks/useScreenCache.ts::useScreenCache::useEffect::d8f2a1226d96::1",
    "apps/web/src/features/shared-session-ui/hooks/useSidebarPreviewTimelineCache.ts::useSidebarPreviewTimelineCache::useEffect::bd41704daafc::1",
    "apps/web/src/features/shared-session-ui/hooks/useUserScrollState.ts::useUserScrollState::useLayoutEffect::8f264547ef6c::1",
    "apps/web/src/lib/use-debounced-callback.ts::useDebouncedCallback::useLayoutEffect::6c2dae421a81::1",
    "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::94e980d9852f::1",
    "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::ba687ecc2fad::1",
    "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::eefa17a2a829::1",
    "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::51694123f2e4::1",
    "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::9c3c8fbff45e::1",
    "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::c0d526106d8a::1",
    "apps/web/src/pages/SessionDetail/hooks/useNoteAutoSave.ts::useNoteAutoSave::useEffect::af6dcf2bb6be::1",
    "apps/web/src/pages/SessionDetail/hooks/useNoteAutoSave.ts::useNoteAutoSave::useEffect::d358dd2415f9::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenMode.ts::useScreenMode::useEffect::a54b0ed920f2::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenScroll.ts::useScreenScroll::useLayoutEffect::12e7f61cf8e9::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenStream.ts::useScreenStream::useEffect::9a2f25ff64af::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionCommits.ts::useSessionCommits::useEffect::db053c8b2d4e::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionCommits.ts::useSessionCommits::useLayoutEffect::2fe58bc42767::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDetailTimelineLogsActions.ts::useSessionDetailTimelineLogsActions::useEffect::88096c9c6c5e::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDiffs.ts::useSessionDiffs::useEffect::c5cc34a77de6::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDiffs.ts::useSessionDiffs::useLayoutEffect::ea501012ebea::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles.ts::useSessionFiles::useEffect::9fc3f1878009::1",
    "apps/web/src/pages/SessionList/components/SessionListHeader.tsx::SessionListSearchInput::useEffect::7b3e63f988b9::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::10c0d27a3cf0::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::4ffa8e6d6624::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::5787ca9d430f::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::8ebfa7493710::1",
    "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::971c94985112::1",
  ],
  "identity-reset": [
    "apps/web/src/features/launch-agent/ResumeWorktreeDialog.tsx::ResumeWorktreeDialog::useEffect::bcc07de459f1::1",
    "apps/web/src/features/notifications/use-push-notifications.ts::usePushNotifications::useLayoutEffect::26cd9672b5d0::1",
    "apps/web/src/features/shared-session-ui/components/LogModal.tsx::LogModal::useLayoutEffect::8c1e882261b9::1",
    "apps/web/src/features/shared-session-ui/hooks/usePaneSendText.ts::usePaneSendText::useLayoutEffect::657e955b365c::1",
    "apps/web/src/features/shared-session-ui/hooks/useRawInputHandlers.ts::useRawInputHandlers::useEffect::93e786f949fe::1",
    "apps/web/src/pages/ChatGrid/components/ChatGridTile.tsx::useChatGridScreenViewport::useLayoutEffect::f8e55dfb319d::1",
    "apps/web/src/pages/SessionDetail/components/LogFileCandidateModal.tsx::LogFileCandidateModal::useEffect::cbb3ee99b855::1",
    "apps/web/src/pages/SessionDetail/components/SmartScreenViewport.tsx::SmartScreenViewport::useEffect::c5b069e422c7::1",
    "apps/web/src/pages/SessionDetail/hooks/useScopeGuard.ts::useScopeGuard::useLayoutEffect::67aff32bc2aa::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useEffect::6f46129aafbe::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useEffect::ff02e8f42a46::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useLayoutEffect::5dad31ef5090::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenMode.ts::useScreenMode::useLayoutEffect::141e2d21a498::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenPanelWorktreeSelector.ts::useScreenPanelWorktreeSelector::useEffect::ca2a447c6a32::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenScroll.ts::useScreenScroll::useLayoutEffect::5e7bbe17d087::1",
    "apps/web/src/pages/SessionDetail/hooks/useScreenStream.ts::useScreenStream::useEffect::d4707baece23::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionBranches.ts::useSessionBranches::useEffect::a0d1c35a7ae1::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionBranches.ts::useSessionBranches::useLayoutEffect::8bdd8bf32b9a::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionCommits.ts::useSessionCommits::useEffect::ac3fd5e9899a::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionControls.ts::useSessionControls::useEffect::894561abeee9::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDiffs.ts::useSessionDiffs::useEffect::0e12d80a85a7::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionDiffs.ts::useSessionDiffs::useLayoutEffect::1c976834aba4::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionFiles-context-reset-effect.ts::useSessionFilesContextResetEffect::useEffect::3823565bd805::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionRepoNotes.ts::useSessionRepoNotes::useEffect::0cae477dc569::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionRepoNotes.ts::useSessionRepoNotes::useLayoutEffect::5519bc3b8cfd::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionScreen.ts::useSessionScreen::useLayoutEffect::fd0e98efeaf4::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionTimeline.ts::useSessionTimeline::useEffect::9c38ec10e314::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionTimeline.ts::useSessionTimeline::useLayoutEffect::333d45ccc731::1",
    "apps/web/src/pages/SessionDetail/hooks/useSessionVirtualWorktree.ts::useSessionVirtualWorktree::useEffect::c429405b754d::1",
    "apps/web/src/state/session-context.tsx::SessionRuntime::useEffect::2001f977f776::1",
  ],
};

export const reviewedUseEffectEventCandidates = [
  "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::8ebfa7493710::1",
  "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::10c0d27a3cf0::1",
  "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::5787ca9d430f::1",
  "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::971c94985112::1",
  "apps/web/src/state/use-sessions-stream.ts::useSessionsStream::useEffect::4ffa8e6d6624::1",
  "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::9c3c8fbff45e::1",
  "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::c0d526106d8a::1",
  "apps/web/src/lib/use-visibility-polling.ts::useVisibilityPolling::useEffect::51694123f2e4::1",
  "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::94e980d9852f::1",
  "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::eefa17a2a829::1",
  "apps/web/src/features/pull-to-refresh/PullToRefreshContainer.tsx::PullToRefreshContainer::useEffect::b3d236225390::1",
  "apps/web/src/features/shared-session-ui/hooks/useUserScrollState.ts::useUserScrollState::useLayoutEffect::8f264547ef6c::1",
  "apps/web/src/pages/SessionDetail/hooks/useScreenStream.ts::useScreenStream::useEffect::9a2f25ff64af::1",
  "apps/web/src/pages/SessionDetail/hooks/useScreenScroll.ts::useScreenScroll::useLayoutEffect::12e7f61cf8e9::1",
] as const;

export const reviewedRefMirrorEventMigration = [
  "apps/web/src/lib/use-pointer-drag.ts::usePointerDrag::useEffect::ba687ecc2fad::1",
] as const;

export const reviewedRetainedIdentityEffects = [
  "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useEffect::ff02e8f42a46::1",
  "apps/web/src/pages/SessionDetail/hooks/useScreenFetch.ts::useScreenFetch::useEffect::6f46129aafbe::1",
] as const;
